services:
  - type: web
    name: tradingview-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: "20.x"
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      # Ajoutez cette variable pour indiquer à votre application où trouver le navigateur
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/chromium-browser"
      - key: API_KEY
        sync: false         