services:
  - type: web
    name: tradingview-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: "20.x"
      - key: API_KEY
        sync: false         